version: '3'

services:

  client-service:
    build:
      context: .
    image: client-api
    depends_on:
      - mysql-db
    container_name: client-api
    hostname: client-api
    ports:
      - 8080:8080
    networks:
      - client-app

  mysql-db:
    image: mysql
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: book_manager
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - client-app

networks:
  client-app:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 201.10.183.0/25